#!/usr/bin/env python3
"""
Sightline — convert phone_calib.yaml into a pySLAM camera settings file.

WHY THIS EXISTS. calibrate_camera.py (7a) writes the ORB-SLAM3 format. pySLAM does
NOT read that format, and neither failure is graceful:

  1. The `%YAML:1.0` directive on line 1 is OpenCV FileStorage syntax. pySLAM parses
     settings with PyYAML, which dies on it -- yaml.scanner.ScannerError, "while
     scanning a directive", before a single key is read.
  2. ORB-SLAM3 namespaces the intrinsics per camera (`Camera1.fx`); pySLAM reads a
     flat `Camera.fx` (pyslam/config.py:239) and raises KeyError otherwise.
  3. Feature count moves from `ORBextractor.nFeatures` to
     `FeatureTrackerConfig.nFeatures`, and pySLAM expects `Viewer.on`.

The feature count is NOT simply carried across. calibrate_camera.py bakes 1250 into its
output; on the 1280x720 stand-in clip that value cost 1 lost frame, 891 of 1101 poses and
9.89% APE, where 2000 gave 0 lost frames, 1089 poses and 0.83% (RUNBOOK 7d). So 2000 is
the default here and the calib file's value is reported, not obeyed. Override with
--features if a run argues otherwise.

So the walk clip needs BOTH files: phone_calib.yaml stays the archival record of what
the phone measured, and this script derives the pySLAM-loadable copy from it. Do not
hand-edit the derived file -- rerun this instead.

USAGE
    ./.venv/bin/python scripts/make_pyslam_settings.py media/calib/phone_calib.yaml \
        -o vendor/pyslam/settings/SIGHTLINE_PHONE.yaml

Then print the config.yaml block to paste under VIDEO_DATASET:

    ... --clip-dir ./data/videos/phone_walk --clip walk.mp4
"""
import argparse
import os
import sys

import cv2


def read_orbslam_yaml(path):
    """Read the ORB-SLAM3 file with OpenCV's FileStorage -- the only reader that
    accepts the %YAML:1.0 directive it opens with."""
    fs = cv2.FileStorage(path, cv2.FILE_STORAGE_READ)
    if not fs.isOpened():
        sys.exit(f"Cannot open {path!r} as an OpenCV YAML file.")

    def num(key, default=None):
        node = fs.getNode(key)
        if node.empty():
            if default is None:
                sys.exit(f"{path}: missing required key {key!r}")
            return default
        return float(node.real())

    vals = {
        "fx": num("Camera1.fx"), "fy": num("Camera1.fy"),
        "cx": num("Camera1.cx"), "cy": num("Camera1.cy"),
        "k1": num("Camera1.k1", 0.0), "k2": num("Camera1.k2", 0.0),
        "p1": num("Camera1.p1", 0.0), "p2": num("Camera1.p2", 0.0),
        "k3": num("Camera1.k3", 0.0),
        "width": int(num("Camera.width")), "height": int(num("Camera.height")),
        "fps": num("Camera.fps", 30.0),
        "rgb": int(num("Camera.RGB", 1)),
        "nfeatures": int(num("ORBextractor.nFeatures", 2000)),
    }
    fs.release()
    return vals


TEMPLATE = """\
# Sightline phone camera -- pySLAM settings.
#
# GENERATED by scripts/make_pyslam_settings.py from {src}
# Do not hand-edit; rerun the script. Valid ONLY for {width}x{height} from the phone,
# lens and zoom that shot the calibration stills.

#-------------------------------------------------------------------------------
# Viewer
#-------------------------------------------------------------------------------
Viewer.on: {viewer}

Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500

#-------------------------------------------------------------------------------
# Camera
#-------------------------------------------------------------------------------
Camera.fx: {fx:.6f}
Camera.fy: {fy:.6f}
Camera.cx: {cx:.6f}
Camera.cy: {cy:.6f}

Camera.k1: {k1:.6f}
Camera.k2: {k2:.6f}
Camera.p1: {p1:.6f}
Camera.p2: {p2:.6f}
Camera.k3: {k3:.6f}

Camera.width: {width}
Camera.height: {height}
Camera.fps: {fps:.1f}

# 0: BGR, 1: RGB -- ignored for greyscale
Camera.RGB: {rgb}

#-------------------------------------------------------------------------------
# Features
#-------------------------------------------------------------------------------
FeatureTrackerConfig.nFeatures: {nfeatures}
"""

CONFIG_BLOCK = """\
# --- paste over the VIDEO_DATASET block in vendor/pyslam/config.yaml ---
VIDEO_DATASET:
  type: video
  sensor_type: mono
  base_path: {clip_dir}
  settings: {settings_rel}
  name: {clip}
  # NO groundtruth_file and NO timestamps keys. A phone walk has neither, and pySLAM
  # raises FileNotFoundError if the key is present but the file is not
  # (pyslam/io/dataset.py:211). Absent keys fall through cleanly to
  # GroundTruthType.NONE (pyslam/io/ground_truth.py:150).
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("calib", help="phone_calib.yaml from calibrate_camera.py")
    ap.add_argument("-o", "--out", default="vendor/pyslam/settings/SIGHTLINE_PHONE.yaml")
    ap.add_argument("--features", type=int, default=2000,
                    help="FeatureTrackerConfig.nFeatures (default 2000; see the module "
                         "docstring for the measurement behind that number)")
    ap.add_argument("--viewer", type=int, choices=(0, 1), default=0,
                    help="Viewer.on (default 0 -- pangolin does not build, see RUNBOOK 7c)")
    ap.add_argument("--clip-dir", default="./data/videos/phone_walk",
                    help="VIDEO_DATASET base_path, relative to the pySLAM root")
    ap.add_argument("--clip", default="walk.mp4", help="VIDEO_DATASET video filename")
    args = ap.parse_args()

    v = read_orbslam_yaml(args.calib)
    calib_nfeatures = v["nfeatures"]
    v["nfeatures"] = args.features
    if calib_nfeatures != args.features:
        print(f"note: {os.path.basename(args.calib)} carries "
              f"ORBextractor.nFeatures={calib_nfeatures}; writing {args.features} instead "
              f"(see module docstring)")

    text = TEMPLATE.format(src=os.path.basename(args.calib), viewer=args.viewer, **v)
    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w") as f:
        f.write(text)

    # Self-check: parse it back the way pySLAM will, and assert the keys config.py reads.
    try:
        import yaml
    except ImportError:
        print("WARNING: PyYAML not installed in this venv -- skipping the readback check.\n"
              "         pip install pyyaml, then rerun, before trusting this file.")
    else:
        with open(args.out) as f:
            d = yaml.load(f, Loader=yaml.FullLoader)
        for key in ("Camera.fx", "Camera.fy", "Camera.cx", "Camera.cy",
                    "Camera.width", "Camera.height", "Camera.fps"):
            if key not in d:
                sys.exit(f"readback FAILED: {key} missing from {args.out}")
        print(f"readback OK: PyYAML parsed {len(d)} keys, all pySLAM requires are present")

    print(f"\nWrote {args.out}")
    print(f"  {v['width']}x{v['height']} @ {v['fps']:g} fps, "
          f"fx={v['fx']:.2f} fy={v['fy']:.2f} cx={v['cx']:.2f} cy={v['cy']:.2f}")

    settings_rel = args.out
    for marker in ("vendor/pyslam/", "/pyslam/"):
        if marker in settings_rel:
            settings_rel = settings_rel.split(marker, 1)[1]
            break
    print()
    print(CONFIG_BLOCK.format(clip_dir=args.clip_dir, settings_rel=settings_rel,
                              clip=args.clip))


if __name__ == "__main__":
    main()
